# ===========================
# Application
# ===========================
spring.application.name=service-registry
server.port=8761

# ===========================
# Eureka Server Config
# ===========================
# This is the server itself ? don't register with itself or fetch from itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.enable-self-preservation=false

# ===========================
# Actuator
# ===========================
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

